name: sap
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-96.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.5.0
  uuid: ^4.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  data_table_2: ^2.3.5
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^4.0.11
  provider: ^6.0.4
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1
  easy_localization: ^3.0.1
  file_picker: ^8.1.2
  firebase_storage: ^12.3.1
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
